name       : kvantum
version    : 0.10.8
release    : 4
source     :
    - https://github.com/tsujan/Kvantum/archive/V0.10.8.tar.gz : a169a19a05985124a946ae638bee2729adad1544497693d911bb7d15160fd20c
license    : GPL-3.0
component  : desktop.theme
summary    : A Linux SVG-based theme engine for Qt4/Qt5 and KDE
description: |
    A Linux SVG-based theme engine for Qt4/Qt5 and KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake_ninja ../Kvantum
build      : |
    %ninja_build
install    : |
    %ninja_install
