name       : kvantum
version    : 0.10.5
release    : 2
source     :
    - https://github.com/tsujan/Kvantum/archive/V0.10.5.tar.gz : 3174dc68331e286a51c0288f5862363258ee2d11b7b10eac65f3bcb0ced6302e
license    : GPL-3.0
component  : desktop.theme
summary    : A Linux SVG-based theme engine for Qt4/Qt5 and KDE
description: |
    A Linux SVG-based theme engine for Qt4/Qt5 and KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake Kvantum
build      : |
    %make
install    : |
    %make_install
