name       : kvantum
version    : 0.17.0
release    : 9
source     :
    - https://github.com/tsujan/Kvantum/archive/V0.17.0.tar.gz : 2d8eda6d44943a5e12baacae7228856c41e120235a374958c7cb50c39148cbfe
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : A Linux SVG-based theme engine for Qt4/Qt5 and KDE
description: |
    A Linux SVG-based theme engine for Qt4/Qt5 and KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kwindowsystem-devel
setup      : |
    %cmake_ninja ../Kvantum
build      : |
    %ninja_build
install    : |
    %ninja_install
