name       : kvantum
version    : 0.14.1
release    : 7
source     :
    - https://github.com/tsujan/Kvantum/archive/V0.14.1.tar.gz : e9c0404e759e71a6384de42674932527c2c29b5223f3c80af10d36dc269a959b
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : A Linux SVG-based theme engine for Qt4/Qt5 and KDE
description: |
    A Linux SVG-based theme engine for Qt4/Qt5 and KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kwindowsystem-devel
setup      : |
    %cmake_ninja ../Kvantum
build      : |
    %ninja_build
install    : |
    %ninja_install
