name       : kvantum
version    : 0.11.0
release    : 5
source     :
    - https://github.com/tsujan/Kvantum/archive/V0.11.0.tar.gz : a6d84d7d14a425ddc3cb4e255b79eff858879247563e58380b6a66ae276ad308
license    : GPL-3.0
component  : desktop.theme
summary    : A Linux SVG-based theme engine for Qt4/Qt5 and KDE
description: |
    A Linux SVG-based theme engine for Qt4/Qt5 and KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - kwindowsystem-devel
setup      : |
    %cmake_ninja ../Kvantum
build      : |
    %ninja_build
install    : |
    %ninja_install
